name: Node.js CI

on:
  push:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - name: Build Site
      run: npm run build --if-present
      env:
        CI: true
        SHEETS_CRED: ${{ secrets.SHEETS_CRED }}
        SHEETS_TOKEN: ${{ secrets.SHEETS_TOKEN }}
        GEOCODING_API: ${{ secrets.GEOCODING_API }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
      env:
        CI: true
        SHEETS_CRED: ${{ secrets.SHEETS_CRED }}